import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import ManageListsPage from "../components/manage/ManageListsPage";

import { trpc } from "../utils/trpc";

const ManageLists: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ManageListsPage />
    </>
  );
};

export default ManageLists;
